export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAIL = "FETCH_USER_FAIL"
export const FETCH_USER_LIST_REQUEST = "FETCH_USER_LIST_REQUEST"
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS"

export const FETCH_USERCONFIG_REQUEST = "FETCH_USERCONFIG_REQUEST"
export const FETCH_USERCONFIG_SUCCESS = "FETCH_USERCONFIG_SUCCESS"
export const FETCH_USERCONFIG_FAIL = "FETCH_USERCONFIG_FAIL"